### ISSUE TITLE
Update Application model to match new application workflow

### ISSUE THREAD

**Issue by jackxujh** [gcivil-nyu-org/fall2019-cs-gy-6063-team-one#157]

**Comment by jackxujh** [comment]
### Bio
- first name
- last name
- gender
- ethnicity
- address
- phone
- email
- url
- disclosures...

### Cover Letter
- large text field

### Experiences ^
- large text field

### Education ^
- large text field

### Authorization
- work authorization
- immigration status
- etc

^ these sections are not most optimal with large text fields, but they are more viable for now, or we will need to make seperate tables for them, like the answer choices in the _Polls_ app.

**Comment by daisycrego** [comment]
@jackxujh first name, last name, and email are stored in the CustomUser - do we want to give the candidate an option to change any of those fields before submitting their application? Because otherwise, if we don't plan on letting them change those fields, there should be a foreign key reference to the Candidate model in Application, rather than having the 3 redundant individual fields (first name, last name, email).

**Comment by jackxujh** [comment]
Is this comment removed?



On Oct 31, 2019, at 6:00 PM, daisycrego <notifications@github.com<mailto:notifications@github.com>> wrote:


@jackxujh<https://github.com/jackxujh> first name, last name, and email are stored in the CustomUser - do we want to give the candidate an option to change any of those fields before submitting their application? Because otherwise, if we don't plan on letting them change those fields, there should be a foreign key reference to the Candidate model in Application, rather than having the 3 redundant individual fields (first name, last name, email).

**Comment by daisycrego** [comment]
@jackxujh what will be the choices for gender and ethnicity?

**Comment by daisycrego** [comment]
for phone, i was thinking of using a PhoneField (https://pypi.org/project/django-phone-field/).

**Comment by daisycrego** [comment]
yeah haha i removed it because i was still thinking about adding another part

**Comment by daisycrego** [comment]
More generally, we need to decide which fields we will allow the Candidate to modify at the time they apply. If we allow them to modify every field (e.g. first name, last name, email), then we can't just have a foreign key reference to Candidate in the Application model because the candidate might want to change the field within the application without changing their profile. @surajgovardhangaikwad decide please 🗡

**Comment by jackxujh** [comment]
> @jackxujh what will be the choices for gender and ethnicity?

Good question! Given that these topics are kind of sensitive and changing so fast, I don't really feel confident I know what the options to give. I was adapting this section from @ahanif16 @ahanif19 .

**Comment by jackxujh** [comment]
I am thinking that many of these fields will be stored in an application record. This will benefit both employers and candidates. For employers, the content within a given application cannot be changed after submission, so it is final and traceable. For candidates, they can always change their profile after submission, without having to worry new narratives in their application affect previous applications. But I feel we could agree on this.

**Comment by jackxujh** [comment]
As for which fields are modifiable upon application, we can first keep everything editable, and see if things work well. Then, perhaps add a button to _update my profile with this field_, just like how you do this when submitting an online shopping order. In this way, candidates don't have to go back and forth to fill in forms, which is not the most attractive part of the process. Anyway, more discussion will be helpful.
